#! /bin/sh

sxhkd &

ws1= # code
ws2= # web
ws3= # main
ws4= # media
ws5=• # media

bspc monitor -d 6 7 8 9 0
bspc monitor eDP1 -d $ws1 $ws2 $ws3 $ws4 $ws5
# bspc monitor HDMI2 -d 6 7 8 9 0

bspc config border_width 1
bspc config window_gap 0
bspc config focus_follows_pointer true
bspc config click_to_focus true
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config split_ratio 0.50

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

# Startup
$HOME/.config/bspwm/panel/panel &

# setting background image
feh --randomize --bg-fill ~/.wallpapers
